### ISSUE TITLE
Expose second cli entrypoint to allow exposing subgit as a sub command to plain git

### ISSUE THREAD

**Issue by Grokzen** [dynamist/subgit#8]
Based on the following blog post, we are able to create custom git commands that the `git` tool itself can pick up and use. We want to implement this for subgit as well. This will help to bridge the useability as more people know about git and using things like `git submodules` that we basically want to extend. https://gitbetter.substack.com/p/automate-repetitive-tasks-with-custom

The task is to extend `setup.py` to include a new entrypoint script that will be named and to be compatible with this git-subcommand feature. Build a package of subgit and test this feature out so that we could possibly call something like `git subgit pull` for instance

One major issue with this ticket that needs a solution is the redundancy in our name when added to the end of `git` command. writing git 2 times to run out commands is verbose and redundant. We need to have suggestions or alterations to our name to make this simpler. For instance we could go with `git sub` or `git module` or `git sg` or something completley different. It is within the task to come up with some suggestion, present them to the team and to get an approval and a choice for this command name that we will move forward with.

**Comment by holmboe** [comment]
Solved in e75809e7342a9e06859557a1ed84dfad050bf004 and 80e2337a0946db4c550d3f9800da94b3bafd8af8 which is in release 0.5.1.
